POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "barez",
    "role": "admin",
    "password": "123"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "barez",
    "password": "123"
}

###

GET http://localhost:5000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0ZThlYTI0LTU4MWItNGU1NS1hZGU5LWMyZWRhY2Y1ZTIyZiIsImlhdCI6MTc3NTY5MjU3NCwiZXhwIjoxNzc2Mjk3Mzc0fQ.i0f7Cala3LH6sDme2FUpUVlw51ETo21xijU3xaEgqnE

###

POST http://localhost:5000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0ZThlYTI0LTU4MWItNGU1NS1hZGU5LWMyZWRhY2Y1ZTIyZiIsImlhdCI6MTc3NDk3MTc1NywiZXhwIjoxNzc1NTc2NTU3fQ.27vZC8F7dbFdPhSZ4A8TFtpZb3RqTuChOW8-lLJJmjc

{
    "title": "CODING TIME",
    "description": "Coding usually starts when i get up, and ends when i sleep. With some break abviously."
}

###

PUT http://localhost:5000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0ZThlYTI0LTU4MWItNGU1NS1hZGU5LWMyZWRhY2Y1ZTIyZiIsImlhdCI6MTc3NDk3MTc1NywiZXhwIjoxNzc1NTc2NTU3fQ.27vZC8F7dbFdPhSZ4A8TFtpZb3RqTuChOW8-lLJJmjc

{
    "id": "1",
    "title": "CODING TIME!",
    "description": "Coding usually starts when i get up, and ends when i sleep. With some break abviously."
}

###

DELETE  http://localhost:5000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0ZThlYTI0LTU4MWItNGU1NS1hZGU5LWMyZWRhY2Y1ZTIyZiIsImlhdCI6MTc3NDk3MTc1NywiZXhwIjoxNzc1NTc2NTU3fQ.27vZC8F7dbFdPhSZ4A8TFtpZb3RqTuChOW8-lLJJmjc

{
    "id": "1"
}

###