POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "barez",
    "role": "admin",
    "password": "123"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "barez",
    "password": "123"
}

###

GET http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM4YzJjZjU1LTA0OWUtNDVjZS05NjE3LWVjNzdjZTZjMzkzOCIsImlhdCI6MTc3NzE1NTM3OCwiZXhwIjoxNzc3NzYwMTc4fQ.526Wi5brZXardRqjOsNNOOnU46JjdJtU1BqipluHsWk

###

POST http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM4YzJjZjU1LTA0OWUtNDVjZS05NjE3LWVjNzdjZTZjMzkzOCIsImlhdCI6MTc3NzE1NTM3OCwiZXhwIjoxNzc3NzYwMTc4fQ.526Wi5brZXardRqjOsNNOOnU46JjdJtU1BqipluHsWk

{
    "name": "Groceries",
    "description": "Groceries are the food and household supplies, ranging from produce and dairy to cleaning items. They represent staple items intended for daily household use. Common examples include bread, milk, vegetables, and canned goods."
}

###

PUT http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM4YzJjZjU1LTA0OWUtNDVjZS05NjE3LWVjNzdjZTZjMzkzOCIsImlhdCI6MTc3NzE1NTM3OCwiZXhwIjoxNzc3NzYwMTc4fQ.526Wi5brZXardRqjOsNNOOnU46JjdJtU1BqipluHsWk

{
    "id": "1",
    "name": "Groceries",
    "description": "Groceries are the food and household supplies intended for daily household use. Common examples include bread, milk, vegetables, and canned goods."
}

###

DELETE  http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM4YzJjZjU1LTA0OWUtNDVjZS05NjE3LWVjNzdjZTZjMzkzOCIsImlhdCI6MTc3NzE1NTM3OCwiZXhwIjoxNzc3NzYwMTc4fQ.526Wi5brZXardRqjOsNNOOnU46JjdJtU1BqipluHsWk

{
    "id": "1"
}

###